### PR TITLE
makefile: add DESTDIR-PREFIX-BINDIR combination

### PR DESCRIPTION
**Pull request by xgqt**
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

### CODE REVIEW

**Comment by sasagawa888** [comment]
Thank you.

**Comment by sasagawa888** [comment]
Installation failed with new makefile. I reverted it for this reason. sorry.

**Comment by xgqt** [comment]
could you post the error you encountered during installation?

**Comment by xgqt** [comment]
> could you post the error you encountered during installation?
> […](#)
> On December 4, 2022 11:20:19 PM UTC, kenichi sasagawa ***@***.***> wrote: Installation failed with new makefile. I reverted it for this reason. sorry. -- Reply to this email directly or view it on GitHub: [#76 (comment)](https://github.com/sasagawa888/nprolog/pull/76#issuecomment-1336547006) You are receiving this because you authored the thread. Message ID: ***@***.***>

Cause it works just fine for me

image

**Comment by xgqt** [comment]
The only error I have made that I just noticed is that I removed "local", so the `PREFIX` should be `/usr/local`.

**Pull request merged**
